# Generated by Django 2.2.6 on 2019-10-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=150)),
                ('fuel_burn', models.CharField(max_length=150)),
                ('flight_from', models.CharField(max_length=150)),
                ('flight_to', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
    ]
