# Generated by Django 2.2.6 on 2019-10-09 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=150)),
                ('fuel_burn', models.CharField(max_length=150)),
                ('flight_from', models.CharField(max_length=150)),
                ('flight_to', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=150)),
                ('item_name', models.CharField(max_length=150)),
                ('item_image', models.ImageField(upload_to='static/image/item')),
                ('item_price', models.IntegerField()),
                ('carbon_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('amount', models.IntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=150)),
                ('account_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('cash_balance', models.IntegerField(default=500)),
                ('credit_balance', models.IntegerField(default=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('rounded_price', models.IntegerField()),
                ('green_amount', models.IntegerField()),
                ('green_points', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_user', to='app.Items')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='app.UserProfile')),
            ],
        ),
    ]
