# Generated by Django 2.2.6 on 2019-10-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_flightdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=150)),
                ('item_name', models.CharField(max_length=150)),
                ('item_image', models.ImageField(upload_to='static/image/item')),
                ('item_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teansactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('rounded_price', models.IntegerField()),
                ('green_amount', models.IntegerField()),
                ('green_points', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_user', to='app.Items')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='app.UserProfile')),
            ],
        ),
    ]
