# Generated by Django 2.2.6 on 2019-10-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191010_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_type',
            new_name='bidder',
        ),
    ]
